source 'https://rubygems.org'
ruby '2.3.8', :patchlevel => '459'
gem 'sinatra'
gem 'omniauth-twitter'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'thin'
gem 'haml'
gem 'twitter'
gem 'clockwork'
gem 'mysql2'
gem 'koala'